Repository LarsDevans/eindopdracht.devops-webs5, pull requests merged in 2025-03, with the labels that each got.

#10 Fresh out-of-the-box NestJS project
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: documentation, enhancement, good first issue

#11 Fresh out-of-the-box microservices setup
  apps/clock-service/src/clock-service.controller.spec.ts
  apps/clock-service/src/clock-service.controller.ts
  apps/clock-service/src/clock-service.module.ts
  apps/clock-service/src/clock-service.service.ts
  apps/clock-service/src/main.ts
  apps/clock-service/test/app.e2e-spec.ts
  apps/clock-service/test/jest-e2e.json
  apps/clock-service/tsconfig.app.json
  apps/mail-service/src/mail-service.controller.spec.ts
  apps/mail-service/src/mail-service.controller.ts
  apps/mail-service/src/mail-service.module.ts
  apps/mail-service/src/mail-service.service.ts
  apps/mail-service/src/main.ts
  apps/mail-service/test/app.e2e-spec.ts
  apps/mail-service/test/jest-e2e.json
  apps/mail-service/tsconfig.app.json
  apps/score-service/src/main.ts
  apps/score-service/src/score-service.controller.spec.ts
  apps/score-service/src/score-service.controller.ts
  apps/score-service/src/score-service.module.ts
  apps/score-service/src/score-service.service.ts
  apps/score-service/test/app.e2e-spec.ts
  apps/score-service/test/jest-e2e.json
  apps/score-service/tsconfig.app.json
  apps/submission-service/src/main.ts
  apps/submission-service/src/submission-service.controller.spec.ts
  apps/submission-service/src/submission-service.controller.ts
  apps/submission-service/src/submission-service.module.ts
  apps/submission-service/src/submission-service.service.ts
  apps/submission-service/test/app.e2e-spec.ts
  apps/submission-service/test/jest-e2e.json
  apps/submission-service/tsconfig.app.json
  apps/target-service/src/main.ts
  apps/target-service/src/target-service.controller.spec.ts
  apps/target-service/src/target-service.controller.ts
  apps/target-service/src/target-service.module.ts
  apps/target-service/src/target-service.service.ts
  apps/target-service/test/app.e2e-spec.ts
  apps/target-service/test/jest-e2e.json
  apps/target-service/tsconfig.app.json
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/main.ts
  tsconfig.json
Labels: enhancement, good first issue

#12 Update root project
  apps/read-service/src/main.ts
  apps/read-service/src/read-service.controller.spec.ts
  apps/read-service/src/read-service.controller.ts
  apps/read-service/src/read-service.module.ts
  apps/read-service/src/read-service.service.ts
  apps/read-service/test/app.e2e-spec.ts
  apps/read-service/test/jest-e2e.json
  apps/read-service/tsconfig.app.json
  nest-cli.json
  package.json
Labels: bug

#13 Add initial DevOps setup
  .dockerignore
  .env.example
  Dockerfile
  README.md
  apps/clock-service/src/clock-service.module.ts
  apps/mail-service/src/mail-service.module.ts
  apps/read-service/src/read-service.module.ts
  apps/score-service/src/score-service.module.ts
  apps/submission-service/src/submission-service.module.ts
  apps/target-service/src/target-service.module.ts
  docker-base.yml
  docker-compose.yml
  init-databases.sql
  package-lock.json
  package.json
Labels: documentation, enhancement, good first issue

#16 Add GitHub actions
  .github/workflows/build-and-test.yml
  .github/workflows/static-analysis.yml
  package.json
Labels: enhancement

#15 Setup RabbitMQ as AQMP service
  .env.example
  apps/clock-service/src/main.ts
  apps/mail-service/src/main.ts
  apps/read-service/src/main.ts
  apps/score-service/src/main.ts
  apps/submission-service/src/main.ts
  apps/target-service/src/main.ts
  docker-base.local.yml
  docker-base.yml
  docker-compose.yml
Labels: enhancement

#17 Add GitHub action badges
  .github/workflows/build-and-test.yml
  .github/workflows/static-analysis.yml
  README.md
Labels: documentation, enhancement
