Repository LarsDevans/eindopdracht.devops-webs5, pull requests merged in 2025-04, with the labels that each got.

#19 Setup Swagger and refactor queues
  .env.example
  apps/clock-service/src/clock-service.controller.ts
  apps/clock-service/src/main.ts
  apps/mail-service/src/mail-service.controller.ts
  apps/mail-service/src/main.ts
  apps/read-service/src/main.ts
  apps/score-service/src/main.ts
  apps/score-service/src/score-service.controller.ts
  apps/submission-service/src/main.ts
  apps/submission-service/src/submission-service.controller.ts
  apps/target-service/src/main.ts
  apps/target-service/src/target-service.controller.ts
  docker-compose.yml
  package-lock.json
  package.json
Labels: enhancement

#21 Add commons library
  libs/README.md
  libs/rmq/src/index.ts
  libs/rmq/src/rmq.module.ts
  libs/rmq/src/rmq.service.ts
  libs/rmq/tsconfig.lib.json
  nest-cli.json
  package.json
  tsconfig.json
Labels: enhancement

#22 Update RabbitMQ queue name configs
  .env.example
  apps/clock-service/src/main.ts
  apps/score-service/src/main.ts
  apps/submission-service/src/main.ts
  apps/target-service/src/main.ts
  docker-compose.yml
  libs/rmq/src/rmq.module.ts
  libs/rmq/src/rmq.service.ts
Labels: enhancement

#25 Create a new target
  apps/mail-service/src/mail.module.ts
  apps/mail-service/src/mail.service.ts
  apps/mail-service/src/targets/targets.controller.ts
  apps/mail-service/src/targets/targets.module.ts
  apps/mail-service/src/templates/target-created.template.ts
  apps/mail-service/src/users/users.module.ts
  apps/mail-service/src/users/users.service.ts
  apps/target-service/src/dto/create-target.dto.ts
  apps/target-service/src/entities/target.entity.ts
  apps/target-service/src/main.ts
  apps/target-service/src/target-service.controller.spec.ts
  apps/target-service/src/target-service.controller.ts
  apps/target-service/src/target-service.module.ts
  apps/target-service/src/target-service.service.ts
  apps/target-service/src/target.controller.ts
  apps/target-service/src/target.module.ts
  apps/target-service/src/target.service.ts
  apps/target-service/test/app.e2e-spec.ts
  libs/kafka/src/kafka.service.ts
  libs/types/src/topic-payload.interface.ts
  package-lock.json
  package.json
Labels: enhancement

#27 Add gateway
  .env.example
  apps/api-gateway/src/app.controller.ts
  apps/api-gateway/src/app.module.ts
  apps/api-gateway/src/app.service.ts
  apps/api-gateway/src/common/decorators/public.ts
  apps/api-gateway/src/common/http-requests/http-request.module.ts
  apps/api-gateway/src/common/http-requests/http-request.service.ts
  apps/api-gateway/src/config/api.constants.ts
  apps/api-gateway/src/features/auth/auth.controller.ts
  apps/api-gateway/src/features/auth/auth.module.ts
  apps/api-gateway/src/features/auth/auth.service.ts
  apps/api-gateway/src/features/auth/dto/user.dto.ts
  apps/api-gateway/src/features/auth/guards/auth.guard.ts
  apps/api-gateway/src/features/auth/strategies/jwt.strategy.ts
  apps/api-gateway/src/features/auth/utils/jwt.util.ts
  apps/api-gateway/src/features/target/dto/create-target.dto.ts
  apps/api-gateway/src/features/target/target.controller.ts
  apps/api-gateway/src/features/target/target.module.ts
  apps/api-gateway/src/features/target/target.service.ts
  apps/api-gateway/src/features/user/user.entity.ts
  apps/api-gateway/src/features/user/user.module.ts
  apps/api-gateway/src/features/user/user.service.ts
  apps/api-gateway/src/main.ts
  apps/api-gateway/test/app.e2e-spec.ts
  apps/api-gateway/test/jest-e2e.json
  apps/api-gateway/tsconfig.app.json
  apps/mail-service/src/mail.module.ts
  apps/mail-service/src/users/users.controller.ts
  apps/target-service/src/target.controller.ts
  apps/target-service/src/target.module.ts
  apps/target-service/src/target.service.ts
  docker-compose.yml
  init-databases.sql
  libs/types/src/dto/create-target.dto.ts
  libs/types/src/dto/index.ts
  libs/types/src/guards/api-key.guard.ts
  libs/types/src/guards/index.ts
  libs/types/src/index.ts
  nest-cli.json
  package-lock.json
  package.json
Labels: enhancement

#29 Add image to target
  .env.example
  apps/api-gateway/src/features/target/dto/create-target.dto.ts
  apps/api-gateway/src/features/target/target.controller.ts
  apps/target-service/src/entities/target.entity.ts
  apps/target-service/src/main.ts
  apps/target-service/src/target.controller.ts
  apps/target-service/src/target.module.ts
  apps/target-service/src/target.service.ts
  libs/imgbb/src/imgbb.module.ts
  libs/imgbb/src/imgbb.service.ts
  libs/imgbb/src/index.ts
  libs/imgbb/tsconfig.lib.json
  libs/types/src/dto/create-target.dto.ts
  nest-cli.json
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#30 Refactor api-key guard
  apps/submission-service/src/submission-service.module.ts
  apps/target-service/src/target.module.ts
  libs/auth/src/guards/api-key.guard.ts
  libs/auth/src/guards/index.ts
  libs/types/src/guards/index.ts
  libs/types/src/index.ts
Labels: enhancement

#31 Refactor env example auth db
  .env.example
Labels: enhancement

#32 Fix import api-key guard
  apps/submission-service/src/submission-service.module.ts
  apps/target-service/src/target.module.ts
Labels: bug

#33 Fix create target in gateway
  apps/api-gateway/src/features/target/target.controller.ts
Labels: bug

#34 Implement Prometheus and Grafana
  .env.example
  apps/api-gateway/src/app.module.ts
  apps/clock-service/src/clock.module.ts
  apps/mail-service/src/mail.module.ts
  apps/read-service/src/read-service.module.ts
  apps/score-service/src/score-service.module.ts
  apps/submission-service/src/submission-service.module.ts
  apps/target-service/src/target.module.ts
  docker-compose.yml
  libs/prometheus/src/index.ts
  libs/prometheus/src/prometheus.controller.ts
  libs/prometheus/src/prometheus.module.ts
  libs/prometheus/src/prometheus.service.ts
  libs/prometheus/tsconfig.lib.json
  nest-cli.json
  package-lock.json
  package.json
  prometheus/alert.yml
  prometheus/prometheus.yml
  tsconfig.json
Labels: enhancement

#35 Create, view, and remove submission(s)
  apps/api-gateway/src/common/http-requests/http-request.service.ts
  apps/api-gateway/src/features/submission/dto/.gitkeep
  apps/api-gateway/src/features/submission/dto/create-submission.dto.ts
  apps/api-gateway/src/features/submission/submission.controller.ts
  apps/api-gateway/src/features/submission/submission.module.ts
  apps/api-gateway/src/features/submission/submission.service.ts
  apps/api-gateway/src/features/target/target.controller.ts
  apps/mail-service/src/mail.module.ts
  apps/mail-service/src/mail.service.ts
  apps/mail-service/src/submissions/dto/create-submission.dto.ts
  apps/mail-service/src/submissions/entities/submission.entity.ts
  apps/mail-service/src/submissions/submissions.controller.ts
  apps/mail-service/src/submissions/submissions.module.ts
  apps/mail-service/src/submissions/submissions.service.ts
  apps/mail-service/src/templates/new-target-submission.template.ts
  apps/mail-service/src/templates/submission-created.template.ts
  apps/submission-service/src/entities/submission.entity.ts
  apps/submission-service/src/main.ts
  apps/submission-service/src/submission-service.controller.spec.ts
  apps/submission-service/src/submission-service.controller.ts
  apps/submission-service/src/submission-service.service.ts
  apps/submission-service/src/submission.controller.ts
  apps/submission-service/src/submission.module.ts
  apps/submission-service/src/submission.service.ts
  apps/submission-service/src/targets/dto/target.dto.ts
  apps/submission-service/src/targets/entities/target.entity.ts
  apps/submission-service/src/targets/targets.controller.ts
  apps/submission-service/src/targets/targets.module.ts
  apps/submission-service/src/targets/targets.service.ts
  apps/submission-service/test/app.e2e-spec.ts
  apps/target-service/src/target.module.ts
  libs/auth/src/utils/jwt.util.ts
  libs/types/src/dto/create-submission.dto.ts
  libs/types/src/dto/index.ts
Labels: enhancement

#36 Make DevOps more mature
  docker-base.local.yml
  docker-base.yml
  docker-compose.yml
Labels: enhancement

#38 Add circuit breaker
  .env.example
  apps/api-gateway/src/common/http-requests/http-request.service.ts
  package-lock.json
  package.json
Labels: enhancement

#37 Add service unit tests
  apps/clock-service/src/clock.controller.spec.ts
  apps/clock-service/src/clock.controller.ts
  apps/mail-service/src/mail.service.spec.ts
  apps/submission-service/src/submission.service.spec.ts
  apps/target-service/src/target.service.spec.ts
Labels: enhancement

#39 Get all targets
  apps/api-gateway/src/features/target/target.controller.ts
  apps/api-gateway/src/features/target/target.service.ts
Labels: enhancement

#40 Calculate score based on submission
  .env.example
  apps/api-gateway/src/app.module.ts
  apps/api-gateway/src/config/api.constants.ts
  apps/api-gateway/src/features/score/score.controller.ts
  apps/api-gateway/src/features/score/score.module.ts
  apps/api-gateway/src/features/score/score.service.ts
  apps/api-gateway/src/features/submission/submission.controller.ts
  apps/mail-service/src/mail.service.ts
  apps/mail-service/src/score/score.controller.ts
  apps/mail-service/src/templates/winner.template.ts
  apps/score-service/src/dto/compare-images.dto.ts
  apps/score-service/src/main.ts
  apps/score-service/src/score-service.controller.spec.ts
  apps/score-service/src/score-service.controller.ts
  apps/score-service/src/score-service.module.ts
  apps/score-service/src/score-service.service.ts
  apps/score-service/src/score.controller.ts
  apps/score-service/src/score.module.ts
  apps/score-service/src/score.service.ts
  apps/score-service/src/submissions/dto/create-submission.dto.ts
  apps/score-service/src/submissions/entity/submission.entity.ts
  apps/score-service/src/submissions/submissions.controller.ts
  apps/score-service/src/submissions/submissions.module.ts
  apps/score-service/src/submissions/submissions.service.ts
  apps/score-service/src/targets/dto/create-target.dto.ts
  apps/score-service/src/targets/entity/target.entity.ts
  apps/score-service/src/targets/targets.controller.ts
  apps/score-service/src/targets/targets.module.ts
  apps/score-service/src/targets/targets.service.ts
  apps/score-service/test/app.e2e-spec.ts
  apps/score-service/test/score.service.spec.ts
  apps/target-service/src/target.module.ts
  libs/imagga/src/config/imagga.config.ts
  libs/imagga/src/config/index.ts
  libs/imagga/src/imagga.module.ts
  libs/imagga/src/imagga.service.ts
  libs/imagga/src/index.ts
  libs/imagga/tsconfig.lib.json
  nest-cli.json
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#41 Weird referencing issue
  apps/mail-service/src/mail.module.ts
Labels: bug, enhancement
